export const projects = [
  {
    title: 'SunnyBooth',
    status: 'Live',
    desc: 'Digital photo booth for capturing, customizing, and sharing memorable moments.',
    link: 'https://sunnybooth.vercel.app/',
    img: '/SunnyBoothbanner.png',
    stack: ['Next.js', 'TypeScript', 'Vercel'],
  },
  {
    title: 'SunnyBooth AI Feedback Automation',
    status: 'Private',
    desc: 'Automated workflow for analyzing feedback, tracking issues, sending alerts, and generating weekly AI reports.',
    link: null,
    img: '/sunnybooth-ai-workflow.png',
    stack: ['n8n Automation', 'Google Gemini', 'Baserow'],
  },
  {
    title: 'Attack on Titan Wiki',
    status: 'Live',
    desc: 'Flutter web app for exploring characters, Titans, favorites, and a Scout quiz.',
    link: 'https://aot-wiki.vercel.app/',
    img: '/project banner (1600 x 800 px).png',
    stack: ['Flutter', 'Dart', 'Web'],
    mobilePreview: true,
  },
  {
    title: 'Foresight',
    status: 'Private',
    desc: 'AI image manipulation timeline analyzer with lightweight forensic signal reporting.',
    link: null,
    img: '/Foresight.png',
    stack: ['Next.js', 'Python', 'AI'],
  },
  {
    title: 'Event Documentation Gallery',
    status: 'Confidential',
    desc: 'Event gallery for preserving memories through organized and accessible photo documentation.',
    link: null,
    img: '/Documentation%20page.png',
    stack: ['Documentation', 'UI Design', 'Workflow'],
  },
  {
    title: 'Procurement Management',
    status: 'Confidential',
    desc: 'Operational procurement interface for tracking requests, reviewing records, and supporting clearer purchasing workflows.',
    link: null,
    img: '/procurement.png',
    stack: ['Dashboard', 'Data Tracking', 'Operations'],
  },
  {
    title: 'Project Unknown',
    status: 'Coming Soon',
    desc: 'Something new is taking shape behind the scenes. Stay tuned.',
    link: null,
    img: null,
    stack: [],
  },
]
