import {
  SiAirtable,
  SiBaserow,
  SiCanvas,
  SiClaude,
  SiCloudflare,
  SiCss,
  SiDart,
  SiFastapi,
  SiFigma,
  SiFlutter,
  SiGit,
  SiGithub,
  SiGithubcopilot,
  SiGmail,
  SiGooglegemini,
  SiGooglesheets,
  SiHtml5,
  SiJavascript,
  SiMake,
  SiN8N,
  SiNextdotjs,
  SiOpenaigym,
  SiOpenapiinitiative,
  SiPython,
  SiRailway,
  SiReact,
  SiScrapy,
  SiSelenium,
  SiSupabase,
  SiTailwindcss,
  SiTypescript,
  SiVercel,
  SiVite,
  SiZapier,
} from 'react-icons/si'
import { FaNodeJs, FaRegFileExcel, FaSpider } from 'react-icons/fa'
import { TbApi, TbMessageChatbotFilled, TbSettingsSpark, TbSparkles } from 'react-icons/tb'

export const technologyGroups = [
  {
    title: 'AI Automation',
    items: [
      { name: 'n8n', Icon: SiN8N, color: 'text-pink-500' },
      { name: 'Make', Icon: SiMake, color: 'text-purple-500' },
      { name: 'Zapier', Icon: SiZapier, color: 'text-orange-500' },
      { name: 'GoHighLevel', Icon: TbSettingsSpark, color: 'text-blue-500' },
      { name: 'Retell AI', Icon: TbMessageChatbotFilled, color: 'text-violet-500' },
      { name: 'Airtable', Icon: SiAirtable, color: 'text-yellow-500' },
      { name: 'Baserow', Icon: SiBaserow, color: 'text-emerald-500' },
      { name: 'Supabase', Icon: SiSupabase, color: 'text-emerald-500' },
      { name: 'Web Scraping', Icon: FaSpider, color: 'text-indigo-500' },
      { name: 'APIs', Icon: TbApi, color: 'text-cyan-500' },
    ],
  },
  {
    title: 'Featured Build Stack',
    items: [
      { name: 'n8n Automation', Icon: SiN8N, color: 'text-pink-500' },
      { name: 'Google Gemini', Icon: SiGooglegemini, color: 'text-blue-500' },
      { name: 'Claude', Icon: SiClaude, color: 'text-orange-500' },
      { name: 'Supabase', Icon: SiSupabase, color: 'text-emerald-500' },
      { name: 'Baserow', Icon: SiBaserow, color: 'text-emerald-500' },
      { name: 'Railway', Icon: SiRailway, color: 'text-purple-500' },
      { name: 'Gmail', Icon: SiGmail, color: 'text-red-500' },
      { name: 'Next.js', Icon: SiNextdotjs, color: 'text-gray-900 dark:text-white' },
    ],
  },
  {
    title: 'Frontend',
    items: [
      { name: 'HTML', Icon: SiHtml5, color: 'text-orange-500' },
      { name: 'CSS', Icon: SiCss, color: 'text-blue-500' },
      { name: 'JavaScript', Icon: SiJavascript, color: 'text-yellow-500' },
      { name: 'TypeScript', Icon: SiTypescript, color: 'text-blue-500' },
      { name: 'React', Icon: SiReact, color: 'text-cyan-400' },
      { name: 'Next.js', Icon: SiNextdotjs, color: 'text-gray-900 dark:text-white' },
      { name: 'Tailwind CSS', Icon: SiTailwindcss, color: 'text-cyan-500' },
      { name: 'Vite', Icon: SiVite, color: 'text-purple-500' },
    ],
  },
  {
    title: 'Mobile Development',
    items: [
      { name: 'Flutter', Icon: SiFlutter, color: 'text-sky-500' },
      { name: 'Dart', Icon: SiDart, color: 'text-sky-600' },
    ],
  },
  {
    title: 'Backend & API',
    items: [
      { name: 'Python', Icon: SiPython, color: 'text-blue-500' },
      { name: 'FastAPI', Icon: SiFastapi, color: 'text-emerald-500' },
      { name: 'Node.js', Icon: FaNodeJs, color: 'text-green-600' },
    ],
  },
  {
    title: 'Generative AI',
    items: [
      { name: 'GPT', Icon: SiOpenaigym, color: 'text-emerald-500' },
      { name: 'Gemini', Icon: SiGooglegemini, color: 'text-blue-500' },
      { name: 'GitHub Copilot', Icon: SiGithubcopilot, color: 'text-gray-700 dark:text-gray-100' },
      { name: 'Claude', Icon: SiClaude, color: 'text-orange-500' },
      { name: 'Prompt Engineering', Icon: TbSparkles, color: 'text-purple-500' },
      { name: 'AI Integration', Icon: TbSettingsSpark, color: 'text-cyan-500' },
      { name: 'OpenAI API', Icon: SiOpenapiinitiative, color: 'text-emerald-500' },
      { name: 'Retell AI', Icon: TbMessageChatbotFilled, color: 'text-violet-500' },
      { name: 'AI Chatbots', Icon: TbMessageChatbotFilled, color: 'text-blue-500' },
    ],
  },
  {
    title: 'Design & Prototyping',
    items: [
      { name: 'Canva', Icon: SiCanvas, color: 'text-cyan-500' },
      { name: 'Figma', Icon: SiFigma, color: 'text-purple-500' },
    ],
  },
  {
    title: 'Data Analysis',
    items: [
      { name: 'Python', Icon: SiPython, color: 'text-blue-500' },
      { name: 'Google Sheets', Icon: SiGooglesheets, color: 'text-emerald-600' },
      { name: 'Web Scraping', Icon: FaSpider, color: 'text-indigo-500' },
      { name: 'Scrapy', Icon: SiScrapy, color: 'text-emerald-500' },
      { name: 'Selenium', Icon: SiSelenium, color: 'text-green-500' },
      { name: 'Data Visualization', Icon: SiCanvas, color: 'text-purple-500' },
      { name: 'Excel', Icon: FaRegFileExcel, color: 'text-green-600' },
    ],
  },
  {
    title: 'Tools & Deployment',
    items: [
      { name: 'Vercel', Icon: SiVercel, color: 'text-gray-900 dark:text-white' },
      { name: 'Cloudflare', Icon: SiCloudflare, color: 'text-orange-500' },
      { name: 'GitHub', Icon: SiGithub, color: 'text-gray-800 dark:text-white' },
      { name: 'Git', Icon: SiGit, color: 'text-orange-600' },
    ],
  },
]

export const featuredTechnologies = [
  ...technologyGroups.find((group) => group.title === 'AI Automation').items,
  ...technologyGroups.find((group) => group.title === 'Featured Build Stack').items,
  ...technologyGroups.find((group) => group.title === 'Generative AI').items,
]
